---
driver:
  name: vagrant

platforms:
  - name: ubuntu-12.04
    driver:
      network:
        - ['public_network', bridge: 'en0: Wi-Fi (AirPort)']
        - ['private_network', ip: '192.168.33.33']

suites:
  - name: chef_solo_latest
    provisioner:
      name: chef_solo
    run_list:
      - recipe[test_cookbook::default]
    attributes:
  - name: chef_zero_12.6
    provisioner:
      name: chef_zero
      require_chef_omnibus: 12.6
    run_list:
      - recipe[test_cookbook::default]
    attributes:
  - name: chef_zero_latest
    provisioner:
      name: chef_zero
    run_list:
      - recipe[test_cookbook::default]
    attributes:
